// Generated by CoffeeScript 1.6.3
var DustCompiler, dust, systemPath;

dust = require('dustjs-linkedin');

systemPath = require('path');

module.exports = DustCompiler = (function() {
  DustCompiler.prototype.brunchPlugin = true;

  DustCompiler.prototype.type = 'template';

  DustCompiler.prototype.extension = 'dust';

  function DustCompiler(config) {
    this.config = config;
    null;
  }

  DustCompiler.prototype.compile = function(data, path, callback) {
    var content, contentJSON, err, error, pathDirs, pathSplit, result;
    try {
      pathSplit = path.split('/');
      pathDirs = pathSplit.length;
      path = pathDirs > 1 ? pathSplit[pathDirs - 1] : pathSplit[0];
      content = dust.compile(data, path.replace(/\.dust/, ''));
      contentJSON = JSON.stringify(content);
      return result = "module.exports = " + content + ";";
    } catch (_error) {
      err = _error;
      return error = err;
    } finally {
      callback(error, result);
    }
  };

  DustCompiler.prototype.include = function() {
    return [systemPath.join(__dirname, '..', '..', 'dustjs-linkedin', 'dist', 'dust-core-2.0.2.js')];
  };

  return DustCompiler;

})();
