// Generated by CoffeeScript 1.6.3
var DustCompiler, dust, systemPath;

dust = require('dustjs-linkedin');

systemPath = require('path');

module.exports = DustCompiler = (function() {
  DustCompiler.prototype.brunchPlugin = true;

  DustCompiler.prototype.type = 'template';

  DustCompiler.prototype.extension = 'dust';

  function DustCompiler(config) {
    this.config = config;
    null;
  }

  DustCompiler.prototype.compile = function(data, path, callback) {
    var content, err, error, name, result, _ref;
    try {
      if ((_ref = this.config.modules) != null ? _ref.nameCleaner : void 0) {
        path = this.config.modules.nameCleaner(path);
      }
      name = path.replace(/\.dust$/, '');
      console.log("name:", name);
      content = dust.compile(data, name);
      return result = "" + content + "\nif (typeof module !== 'undefined') {\n  module.exports = function(context, callback) {\n    dust.render(" + (JSON.stringify(name)) + ", context, callback);\n  };\n}";
    } catch (_error) {
      err = _error;
      return error = err;
    } finally {
      callback(error, result);
    }
  };

  DustCompiler.prototype.include = function() {
    return [systemPath.join(__dirname, '..', '..', 'dustjs-linkedin', 'dist', 'dust-core-2.0.2.js')];
  };

  return DustCompiler;

})();
