// Generated by CoffeeScript 1.6.3
var DustCompiler, dust, systemPath;

dust = require('dustjs-linkedin');

systemPath = require('path');

module.exports = DustCompiler = (function() {
  DustCompiler.prototype.brunchPlugin = true;

  DustCompiler.prototype.type = 'template';

  DustCompiler.prototype.extension = 'dust';

  function DustCompiler(config) {
    var _ref, _ref1;
    this.config = config;
    if ((_ref = this.config.plugins) != null ? (_ref1 = _ref.dust) != null ? _ref1.retainWhitespace : void 0 : void 0) {
      dust.optimizers.format = function(ctx, node) {
        return node;
      };
    }
  }

  DustCompiler.prototype.compile = function(data, path, callback) {
    var content, err, error, name, result, _ref;
    try {
      if ((_ref = this.config.modules) != null ? _ref.nameCleaner : void 0) {
        path = this.config.modules.nameCleaner(path);
      }
      name = path.replace(/\.dust$/, '');
      content = dust.compile(data, name);
      return result = "var tmpl = " + content + "\nmodule.exports = tmpl;\nmodule.exports.render = function(context, callback) {\n  dust.render(" + (JSON.stringify(name)) + ", context, callback);\n};\nmodule.exports.stream = function(context) {\n  return dust.stream(" + (JSON.stringify(name)) + ", context);\n};";
    } catch (_error) {
      err = _error;
      return error = err;
    } finally {
      callback(error, result);
    }
  };

  DustCompiler.prototype.include = function() {
    var modulePath, moduleRoot;
    modulePath = require.resolve('dustjs-linkedin');
    moduleRoot = systemPath.join(modulePath, '..', '..');
    return systemPath.join(moduleRoot, 'dist', 'dust-core.js');
  };

  return DustCompiler;

})();
